version: '2'
services:

  frontend:
    build: ./frontend
    container_name: Face_Your_Knuckles_frontend
    command: npm run start
    ports:
      - '8080:80'
    volumes:
     - ./frontend:/app
    environment:
      NODE_ENV: development

  backend:
    build: ./backend
    container_name: Face_Your_Knuckles_backend
    command: php artisan serve
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app